<a href="https://colab.research.google.com/github/ilham-mukti/Machine-Learning/blob/main/data_teks/Document_Similarity_%26_Keyword_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mencari Similarity Document
Caranya dengan encode dlu menggunakan tfidf, kemudian cari similaritynya

In [3]:
import nltk
nltk.download("stopwords")
nltk.download("punkt")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [28]:
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from string import punctuation
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

sw_indo = stopwords.words("indonesian") + list(punctuation)

In [5]:
datas = pd.read_csv("/content/kompas.csv")
datas.head()

teks
0  Ginandjar Tetap Ditahan. Jaksa Agung Dilaporka...
1  Jakarta Dikangkangi Para Preman\nKALAU tak pun...
2  Penyimpangan di Setpres Seolah Terjadi Sekaran...
3  Dibayarkan, Rapel Kenaikan Gaji Pegawai Pos\nK...
4  Stop Kekerasan, Elite agar Duduk Bersama\nSeju...

In [7]:
datas.teks[0][:200]

'Ginandjar Tetap Ditahan. Jaksa Agung Dilaporkan ke Polri\nKejaksaan Agung memutuskan untuk tetap menahan tersangka kasus korupsi, Ginandjar Kartasasmita, sampai batas waktu yang ditentukan KUHAP. Sedan'

## Extract TFIDF

In [112]:
tfidf = TfidfVectorizer(ngram_range=(1,2), tokenizer=word_tokenize, stop_words=sw_indo)
tfidf_matrix = tfidf.fit_transform(datas.teks)
tfidf_matrix

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['``'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


<2008x548406 sparse matrix of type '<class 'numpy.float64'>'
	with 1173616 stored elements in Compressed Sparse Row format>

## Document Similarity

In [83]:
sim = cosine_similarity(tfidf_matrix[1], tfidf_matrix)
sim

array([[0.00858328, 1.        , 0.01030995, ..., 0.01237804, 0.03707573,
        0.01835452]])

In [95]:
sorted_sim = sim[0].argsort() #Ini emang 0, supaya jadi array vektor
sorted_sim

array([1230, 1593,  567, ...,  239,  172,    1])

In [104]:
berita_yang_sama = [datas.teks[index][:100] for index in reversed(sorted_sim[-10:])]
berita_yang_sama

['Jakarta Dikangkangi Para Preman\nKALAU tak punya nyali dan uang cukup, jangan berjualan di sekitar Te',
 'Preman dari yang di Jalanan hingga yang Berdasi\nRENCANA Musyawarah Pimpinan Daerah (Muspida) DKI Jak',
 '"Kunjungan Wisata" Pemberantasan Preman...\nBUNYI sirene motor-motor  voorrijder -pengawal bermotor-m',
 'Di Kuburan Pun Ada Preman\nDI Medan, kota yang disebut-sebut sebagai tempat asalnya, sepak terjang pr',
 'Aksi Preman di Pasar Kramat Jati\n\nBENTROKAN massal yang nyaris terjadi di Pasar Kramat Jati, Jakarta',
 'Aksi Preman Merajalela di Sawah-sawah Pantura\nPREMAN mudah dicari di terminal, pasar, dan pusat kera',
 'Tentara "Bersihkan" Preman di PLB Entikong\n\nSejumlah petugas TNI dari kesatuan Komando Distrik Milit',
 'Pedagang Kaki Lima Bentrok dengan Petugas\nOperasi pedagang kaki lima dan preman yang dilakukan tim p',
 'Gedung Balaikota Bandung Dirusak Pedagang Kaki Lima\n\nSekitar 500 pedagang kaki lima (PKL) hari Kamis',
 'Operasi Pasar Beras, Bukan Sekadar Berjua

In [22]:
datas.teks[1][:200]

'Jakarta Dikangkangi Para Preman\nKALAU tak punya nyali dan uang cukup, jangan berjualan di sekitar Terminal Pulogadung Jakarta Timur. Belum lagi barang dagangan digelar, sudah harus membayar sewa lahan'

In [23]:
datas.teks[172][:200]

'Preman dari yang di Jalanan hingga yang Berdasi\nRENCANA Musyawarah Pimpinan Daerah (Muspida) DKI Jakarta untuk memerangi preman di Ibu Kota disambut dengan dingin oleh masyarakat. Warga umumnya merasa'

In [24]:
datas.teks[239][:200]

'"Kunjungan Wisata" Pemberantasan Preman...\nBUNYI sirene motor-motor  voorrijder -pengawal bermotor-memecahkan kesibukan warga di sekitar Pasar Tanah Abang, Jakarta Pusat, Senin (16/4). Pengawal bermot'

In [116]:
#Jadiin fungsi biar gampang
def document_similarity(index, matrix, topk=10):
  sim = cosine_similarity(matrix[index], matrix)
  sorted_sim = sim[0].argsort()
  berita_yang_sama = [datas.teks[index][:100] for index in reversed(sorted_sim[-topk:])]
  return(berita_yang_sama)

In [117]:
data_ke = 1
document_similarity(data_ke, tfidf_matrix)

['Jakarta Dikangkangi Para Preman\nKALAU tak punya nyali dan uang cukup, jangan berjualan di sekitar Te',
 'Preman dari yang di Jalanan hingga yang Berdasi\nRENCANA Musyawarah Pimpinan Daerah (Muspida) DKI Jak',
 '"Kunjungan Wisata" Pemberantasan Preman...\nBUNYI sirene motor-motor  voorrijder -pengawal bermotor-m',
 'Di Kuburan Pun Ada Preman\nDI Medan, kota yang disebut-sebut sebagai tempat asalnya, sepak terjang pr',
 'Aksi Preman di Pasar Kramat Jati\n\nBENTROKAN massal yang nyaris terjadi di Pasar Kramat Jati, Jakarta',
 'Aksi Preman Merajalela di Sawah-sawah Pantura\nPREMAN mudah dicari di terminal, pasar, dan pusat kera',
 'Tentara "Bersihkan" Preman di PLB Entikong\n\nSejumlah petugas TNI dari kesatuan Komando Distrik Milit',
 'Pedagang Kaki Lima Bentrok dengan Petugas\nOperasi pedagang kaki lima dan preman yang dilakukan tim p',
 'Gedung Balaikota Bandung Dirusak Pedagang Kaki Lima\n\nSekitar 500 pedagang kaki lima (PKL) hari Kamis',
 'Operasi Pasar Beras, Bukan Sekadar Berjua

# Keyword Extraction

In [45]:
vocab = tfidf.get_feature_names()
vocab[-10:]

['zuniga memilih',
 'zunnatul',
 'zunnatul mafruhah',
 'zurich',
 'zurich northholt',
 'zw',
 'zw suparman',
 'zw tim',
 'zx',
 'zx diserbu']

In [59]:
tfidf_matrix[1].toarray()

array([[0.04703404, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [60]:
sorted_tfidf = tfidf_matrix[1].toarray()[0].argsort()
sorted_tfidf

array([274202, 365427, 365426, ..., 300050, 375703, 427443])

In [61]:
vocab[427443], vocab[375703], vocab[300050]

('preman', 'pedagang', 'memberantas preman')

In [94]:
keyword = [vocab[idx] for idx in reversed(sorted_tfidf[-10:])]
keyword

['preman',
 'pedagang',
 'memberantas preman',
 'pedagang kaki',
 'potmas',
 'uang',
 "'' pedagang",
 'jalan trunojoyo',
 'uang jalan',
 'trunojoyo']

In [102]:
#dibungkus biar enak dipakai:

def extract_keyword_tfidf(doc, tfidf, topk=10):
  matrix = tfidf.transform([doc])
  vocab = tfidf.get_feature_names()

  sorted_tfidf = matrix[0].toarray()[0].argsort()
  return([vocab[idx] for idx in reversed(sorted_tfidf[-topk:])])

In [103]:
text = datas.teks[1]
extract_keyword_tfidf(text, tfidf)

['preman',
 'pedagang',
 'memberantas preman',
 'pedagang kaki',
 'potmas',
 'uang',
 "'' pedagang",
 'jalan trunojoyo',
 'uang jalan',
 'trunojoyo']